name: EC2 Auto-Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote deploy
        env:
          TOKEN: ${{ secrets.OMNEURO_DEPLOY_TOKEN }}
          TARGET: http://18.221.67.174/api/deploy
        run: |
          set -euo pipefail
          curl -fsS -X POST "$TARGET" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"reason\":\"github-actions\",\"repo\":\"${{ github.repository }}\",\"actor\":\"${{ github.actor }}\",\"sha\":\"${{ github.sha }}\"}"